### ISSUE TITLE
REVIEW Week 11

### ISSUE THREAD

**Issue by schwarz-tw** [SOA-GOAT/SECond#23]
#22 is our HW this week.
Heroku Link: https://goat-second.herokuapp.com

**Comment by chinyakao** [comment]
@schwarz-tw @BlauwaLiu @NianHung 

There are some quality issues in rubocop and reek, please take a look.
I saw your problems in slack. I will review that next week.

**Comment by BlauwaLiu** [comment]
@chinyakao We fix the quality issues in #25 . Thanks for the gentle reminder.
